### ISSUE TITLE
minista v4 開発メモ

### ISSUE THREAD

**Issue by qrac** [qrac/minista#121]
## Releases

テーマ：モジュラー化

- すべての機能をViteプラグインとしてリプレイスしつつ強化
- 既存のHTMLをJSXで修正するプラグインを追加
- 静的ページをStorybook風のUIで表示するプラグインを追加

### Features

- DenoとBunで動作
- 本体の依存関係を分散し大幅に軽量化
- 本体無しでもViteとプラグインだけで動作
- HTML・アセットのViteプラグイン処理に対応
- アウトプットファイル名のhashに対応
- 画像（ルートパス）の自動バンドルに対応
- 画像生成にキャッシュを実装
- SVGをimportなしのルートパスのみでインライン展開
- SVGインライン展開時の不要なファイル生成を除去
- SVGインライン展開にSVGO最適化機能を追加
- SVGスプライト内のスタイルをインラインに変換
- SVGスプライトのマージに対応
- SVGスプライトにSVGO最適化機能を追加
- Partial Hydrationの出力JSをページ毎に最適化

### Breaking Changes

- ViteをpeerDependenciesに変更
- Reactの対応バージョンを18以上に変更
- minista.config.tsの内容をvite.config.tsに変更
- 各機能のアクティブ化をViteプラグインに変更
- コンフィグのアセットエントリーを廃止
- Headの参照先をプラグインに変更
- 画像生成オプションのresolutionをresolutionsに変更
- Image・Pictureのresolutionをresolutionsに変更
- Image・PictureのoutNameを削除
- SVGRの仕組みをimportなしのSvgコンポーネントに変更
- IconをSpriteに命名変更・参照先をプラグインに変更
- Partial HydrationのusePreactオプションを削除

## Plans

開発ブランチ: [v4](https://github.com/qrac/minista/tree/v4)

- [x] 実務に最低限のアルファ版を投入して必要になった機能とプラグインを随時リリース
- [ ] 予定している以下のパッケージすべてが完成した時点でv4として公開
- [ ] ドキュメント（v3を配下に内包）とアートワークスの更新

### Packages

- [ ] create-minista
- [x] minista
- [x] minista-plugin-ssg
- [x] minista-plugin-enhance
- [x] minista-plugin-mdx
- [x] minista-plugin-bundle
- [x] minista-plugin-image
- [x] minista-plugin-svg
- [x] minista-plugin-sprite
- [x] minista-plugin-hydrate
- [ ] minista-plugin-search
- [ ] minista-plugin-delivery
- [x] minista-plugin-story
- [x] minista-plugin-beautify
- [x] minista-plugin-archive
- [x] minista-shared-head
- [x] minista-shared-utils

### Tasks

- [x] serverのHMR・ホットリロード
- [x] Headのレンダリング処理
- [x] StoryApp Component
- [x] StoryAppのNavItem型を提供
- [x] StoryAppにローディングアニメーション追加
- [x] bundle buildのHTMLタグ挿入
- [x] 画像の相対パスに対応
- [x] entryにbaseを反映
- [x] Headにclassの型を追加
- [x] SsgPageのtypeの置き場検討
- [x] SVGスプライトのスタイルタグをインライン化
- [x] 既存のSVGスプライトへの追加機能を実装
- [x] fetchの動作確認
- [x] 画像生成のキャッシュ対応
- [ ] StoryAppのモバイル対応
- [ ] StoryAppの目次自動生成
- [ ] Winのパス関連をチェック

**Comment by qrac** [comment]
v3はsharpがBunで動かなくてコケてたけどリポジトリには改善されたと書いてあったのでもう一度試す。動かなくてもプラグインを分割するので問題を切り離せる。

**Comment by qrac** [comment]
エンハンスプラグインの利用シーンイメージ

```tsx
// src
// └── enhance
//     ├── index.html
//     └── index.tsx
function component() {
  return (
    <div className="box">
      <h2>Enhanced About Contents</h2>
    </div>
  )
}

export default function () {
  return [
    {
      component,
      mode: "replace", // "replace" | "insert"
      selector: "section#about > div",
      useSelectorAll: false,
    },
  ]
}
```

HTML内のルートパスをサーバー上の絶対パスに変更する処理も必要そう。

**Comment by qrac** [comment]
エンハンスプラグインはReact componentをHTMLとして挿入できるだけでなく、HTMLの挿入、要素の削除、attributeの修正や正規表現を使った既存の値のreplaceなども行えるようにした。

```tsx

export default function (): EnhancePage {
  return {
    html,
    commands: [
      {
        selector: "html",
        attr: "lang",
        value: "ja",
      },
      {
        selector: `link[href="/css/style2.css"]`,
        method: "remove",
      },
      {
        selectorAll: "script",
        attr: "src",
        pattern: /^\/(.*?)/,
        value: "https://example.com/$1",
      },
      {
        selector: "section#content1 > div",
        html: `<div class="box"><p>html text</p></div>`,
      },
    ],
  }
}

```

**Comment by qrac** [comment]
minista-plugin-appの予定だったものはminista-plugin-mpaに変更。appだとディレクトリ名がassetsより上に来てしまう。

```
app
assets
components
enhance
layouts
pages
stories

↓

assets
components
enhance
mpa
layouts
pages
stories
```

**Comment by qrac** [comment]
プラグインを同時に使用する場合は、ページパスの重複を避けるため拡張子を追加して同居させるのが望ましい。

```
assets
components
layouts
pages
├─ **/*.tsx
├─ **/*.mdx
├─ **/*.mpa.tsx
├─ **/*.enhance.tsx
├─ **/*.stories.tsx
└─ **/*.stories.mdx
```

**Comment by qrac** [comment]
アルファ版をリリースした。実戦で検証を開始。

**Comment by qrac** [comment]
エンハンスStoryApp用立ち上げインストールコマンド。

```sh
$ npm i react react-dom
$ npm i minista@next vite minista-plugin-enhance@next minista-plugin-entry@next minista-plugin-mdx@next minista-plugin-story@next minista-plugin-beautify@next minista-plugin-archive@next
```

**Comment by qrac** [comment]
StoryApp用

```sh
npm i react react-dom
```

```sh
npm i -D minista@next vite typescript @types/node @types/react @types/react-dom
```

```sh
npm i -D  minista-plugin-enhance@next minista-plugin-entry@next minista-plugin-mdx@next minista-plugin-story@next minista-plugin-beautify@next minista-plugin-archive@next
```

**Comment by qrac** [comment]
エンハンスプラグインで無茶苦茶編集すると最終的に何ができあがっているのかイメージしづらくなった。編集箇所を決めること、全体処理とコンポーネントの差し込みをメインにして、基本的な作業はコンポーネント側に渡す方が良さそう。全体リニューアルには向かない。

**Comment by qrac** [comment]
StoryAppにローディングアニメーションを追加する。
開発中にいちいち出るのが鬱陶しかったので削除していたが再実装予定。

NetlifyにアップしたプロトタイプはTTFBがかなり遅くて長いHTMLのロードに数秒時間がかかっている。パスの先が無くてエラーを起こしているのかロード中なのか不明でストレス。

同時にパスが見つかっていない場合の処理も追加する。現状だとindex.htmlが出てしまう。Appがindex.htmlのときにナビゲーションのパスを間違うとiframeが無限入れ子になってしまう。

**Comment by qrac** [comment]
minista-plugin-deliveryの機能は最近使ってないから一旦削除でいいかも。storyapp使って納品してる。

**Comment by qrac** [comment]
minista-plugin-island

babelのparse, traverse, generateを使ってIslandコンポーネント配下を検出しようとしたがesmでうまく動かず。

```
traverse is not a function
```

```js
// defaultを使う形でも動かない？
import traverse from "@babel/traverse"

traverse.default(...)
```

**Comment by qrac** [comment]
#122 の画像生成キャッシュを導入する。

**Comment by qrac** [comment]
Partial Hydrationの動作するReactのバージョンを18以上に変更した。

バージョン検出の実装コードが長く、また確実ではないため。

**Comment by qrac** [comment]
Partial HydrationのusePreactオプションを削除した。

プラグインの影響範囲を超えて他のJavaScriptのビルドにも影響するため。また、依存関係を減らす目的もある。

今後は手動でpreact-compatをビルド全体に対して設定することにする。

**Comment by qrac** [comment]
MPAプラグインは使わなそうなので予定から一旦削除。

**Comment by qrac** [comment]
vituumを参考にSSGプラグインを新しい方法で作ってみたが、coreのHTMLプラグインの挙動をいじれない部分があり破棄。

このプラグインではHTMLファイルを実際に生成してViteのinputに渡す。既存のemitFileで生成結果を差し込む場合と異なり、srcやhrefでルートパスを書いたアセットを簡単にバンドルできる。

ただし、エントリーのスクリプトに不要な内容が含まれたり、エントリーしたCSSの名前が変わったりと実務に向かなかった。

```ts
import type { Plugin, UserConfig } from "vite"
import fs from "node:fs"
import path from "node:path"
import fg from "fast-glob"

import type { SsgPage } from "minista-shared-utils"
import {
  checkDeno,
  getCwd,
  getPluginName,
  getTempName,
  getRootDir,
  getTempDir,
  getHtmlPath,
  getBasedAssetPath,
} from "minista-shared-utils"

import type { ImportedLayouts, ImportedPages } from "../@types/node.js"
import type { PluginOptions } from "./option.js"
import { getGlobExportCode, getSsgExportCode } from "./code.js"
import { formatLayout, resolveLayout } from "./layout.js"
import { formatPages, resolvePages } from "./page.js"
import { transformHtml } from "./html.js"

export function pluginSsgBuild(opts: PluginOptions): Plugin {
  const isDeno = checkDeno()
  const cwd = getCwd(isDeno)
  const names = ["ssg", "build"]
  const pluginName = getPluginName(names)
  const tempName = getTempName(names)
  const regCwd = new RegExp("^" + cwd)

  let isSsr = false
  let base = "/"
  let rootDir = ""
  let tempDir = ""
  let globDir = ""
  let globFile = ""
  let ssrDir = ""
  let ssrFile = ""
  let ssgDir = ""
  let entries: { [key: string]: string } = {}
  let entryChanges: {
    beforeName: string
    afterName: string
  }[] = []

  return {
    name: pluginName,
    enforce: "post",
    apply: "build",
    config: async (config, { command }) => {
      isSsr = config.build?.ssr ? true : false
      base = config.base || base
      rootDir = getRootDir(cwd, config.root || "")
      tempDir = getTempDir(cwd, rootDir)
      globDir = path.join(tempDir, "glob")
      globFile = path.join(globDir, `${tempName}.js`)
      ssrDir = path.join(tempDir, "ssr")
      ssrFile = path.join(ssrDir, `${tempName}.mjs`)
      ssgDir = path.join(tempDir, "ssg")

      if (isSsr) {
        const code = getGlobExportCode(opts)
        await fs.promises.mkdir(globDir, { recursive: true })
        await fs.promises.writeFile(globFile, code, "utf8")

        return {
          build: {
            rollupOptions: {
              input: {
                [tempName]: globFile,
              },
              output: {
                chunkFileNames: "[name].mjs",
                entryFileNames: "[name].mjs",
              },
            },
            outDir: ssrDir,
          },
          ssr: {
            external: ["minista-shared-head"],
          },
        } as UserConfig
      }

      if (!isSsr) {
        const htmlFiles = await fg(path.join(ssgDir, `**/*.html`))
        const regRootDirSlash = new RegExp("^" + rootDir + "[/\\\\]")
        const redSsgDirSlash = new RegExp("^" + ssgDir + "[/\\\\]")

        for (const htmlFile of htmlFiles) {
          const htmlKey = htmlFile
            .replace(regCwd, "")
            .replace(/\//g, "_")
            .replace(/\\/g, "_")
            .replace(/\./g, "_")
          entries[htmlKey] = htmlFile

          const beforeName = htmlFile.replace(regRootDirSlash, "")
          const afterName = htmlFile.replace(redSsgDirSlash, "")

          entryChanges.push({ beforeName, afterName })
        }
        //console.log("entryChanges: ", entryChanges)
        return {
          build: {
            rollupOptions: {
              input: entries,
            },
          },
        }
      }
    },
    generateBundle(options, bundle) {
      if (!isSsr) {
        const diffDir = path.relative(ssgDir, rootDir)
        const upDirCount = diffDir
          .split(/[/\\]/)
          .filter((part) => part === "..").length
        const upDirString = "../".repeat(upDirCount)

        //console.log("generateBundle: ", bundle)
        for (const entryChange of entryChanges) {
          const { beforeName, afterName } = entryChange

          if (bundle[beforeName]) {
            bundle[beforeName].fileName = afterName
          }
        }
        //console.log("generateBundle: ", bundle)
      }
    },
    async writeBundle(options, bundle) {
      if (isSsr) {
        const { LAYOUTS, PAGES } = (await import(ssrFile)) as {
          LAYOUTS: ImportedLayouts
          PAGES: ImportedPages
        }
        const formatedLayout = formatLayout(LAYOUTS)
        const resolvedLayout = await resolveLayout(formatedLayout)
        const formatedPages = formatPages(PAGES, opts)
        const resolvedPages = await resolvePages(formatedPages)
        const ssgPages = resolvedPages.map((resolvedPage) => {
          const fileName = getHtmlPath(resolvedPage.path)
          const html = transformHtml({ resolvedLayout, resolvedPage })
          return { fileName, html }
        })
        await Promise.all(
          ssgPages.map(async (ssgPage) => {
            const filePath = path.join(ssgDir, ssgPage.fileName)
            const fileDir = path.dirname(filePath)
            const code = ssgPage.html
            await fs.promises.mkdir(fileDir, { recursive: true })
            await fs.promises.writeFile(filePath, code, "utf8")
          })
        )
      }
    },
  }
}
```

**Comment by qrac** [comment]
plugin-bundleとplugin-entryのHTML処理が重複するためplugin-bundleに統合する。画像のsrcエントリーにも対応。plugin-ssgに含まれる画像の相対パスに関する修正もplugin-bundleに移動する。

- テンプレートのルートパスから CSS・JS・画像をエントリー
- テンプレートでインポートした CSS を結合して出力
- テンプレートでインポートした画像を出力

**Comment by qrac** [comment]
v3のSVGスプライトの変換にはスタイルタグのインライン化機能が入っていないので `svgo` などを使う。
`svg-sprite` に `svgo` を使うオプションがあるので、それを利用する。
ついでに、既存のスプライトへの追加もやりたかったので実装する。

**Comment by qrac** [comment]
`Image` コンポーネントのloadingなどのデフォルト設定をオプションに作る。`lazy` はGoogleの点数は上がるが体感的にはスクロール中に画像が遅れてうんざりする場合あり。

**Comment by qrac** [comment]
fetchはalpha-8で問題なく動作することを確認。node 18に含まれているundiciのfetchを自動的にimport不要で使用。

```sh
> build
> minista build

vite v5.3.5 building SSR bundle for production...
✓ 3 modules transformed.
node_modules/.minista/ssr/__minista_ssg_build.mjs  1.96 kB
✓ built in 117ms
vite v5.3.5 building for production...
✓ 1 modules transformed.
dist/index.html       0.45 kB │ gzip: 0.36 kB
dist/issues/115.html  0.55 kB │ gzip: 0.65 kB
dist/issues/114.html  0.60 kB │ gzip: 0.50 kB
dist/issues/113.html  0.61 kB │ gzip: 0.53 kB
dist/issues/118.html  1.64 kB │ gzip: 1.78 kB
dist/issues/121.html  1.92 kB │ gzip: 1.53 kB
✓ built in 45ms
```

**Comment by qrac** [comment]
型が取得できない。

```ts
import type { StaticData, PageProps } from "minista-plugin-ssg/client"
```

**Comment by qrac** [comment]
Image・PictureのpropsからoutNameを削除する。使わない割に画像生成の仕組みやキャッシュ生成の分岐が複雑になるため。AstroのImageやAstro Imagetoolsにもないので一般的に望まれている機能ではないとも思う。

**Comment by qrac** [comment]
v3の画像最適化はHTMLのパース・画像生成・HTMLタグの書き換えを同時におこなっていたが、Viteプラグインにする場合は分離させる必要がある。

- SSRビルド時にコンポーネントのプロパティ置換
- ビルドエントリー前にHTMLのパース・画像生成・キャッシュ生成
- すべての画像をViteにエントリーしてビルドプロセスに組み込む
- ビルド後のHTMLをパースしてタグを書き換え

**Comment by qrac** [comment]
参考にしているvite-plugin-svgrのimport方法が変わっていたので準じて変更予定。ファイルが出力されてしまう問題も解決している？SVGOの最適化どうしていたかも確認する。

```ts
// Before
import { ReactComponent as Logo } from "./logo.svg";

// After
import Logo from "./logo.svg?react";
```

- https://www.npmjs.com/package/vite-plugin-svgr
- https://github.com/pd4d10/vite-plugin-svgr

**Comment by qrac** [comment]
SVGRの実装、importしないでルートパスから裏で読み取ればファイルも出力されないから良いのでは？

```tsx
import { Svgr } from "minista-plugin-svgr"

export default function () {
  return <Svgr src="/src/assets/logo.svg" />
} 
```

**Comment by qrac** [comment]
search, delivery, storyの自動で全体のコンテンツを取得する機能を実装するには、事前に1箇所にSSGした共通フォーマットのファイルを用意しなければならない。

本番ビルドは一方通行なので簡単だが、開発モードの時に少エネで動作させ続けるには？ページレンダリング時に毎回生成するのではなく機能にアクセスした時に生成するとか？機能の補助をssgやenhanceなどに持たせずsearchのみで完結させる？

**Comment by qrac** [comment]
案: `minista-plugin-remote-public`

- dev, build前にリモート素材をDLしてtempに追加したpublicエリアに配置するプラグイン
- 配列でアセットのDL URLと本番パスを指定
- キャッシュがあればDLを迂回

**Comment by qrac** [comment]
プラグインの公開やインストールが面倒なのでministaの中にパーテーションでプラグインを内蔵して使えるようにする。

**Comment by qrac** [comment]
2025年は新しく書き直すので、こちらはクローズ。 #131
